package consts

// Code generated by sqlset-gen. DO NOT EDIT.
// Source: github.com/istovpets/sqlset.

// Generated by this command:
// go run github.com/istovpets/sqlset/cmd/sqlset-gen --dir=../queries/ --out=queries-gen.go --pkg=consts

// users.sql
var Users = struct {
	CreateUser  string
	GetUserByID string
}{
	CreateUser:  "users.CreateUser",
	GetUserByID: "users.GetUserByID",
}
