package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/istovpets/sqlset"
)

// To test generation:
//go:generate go run github.com/istovpets/sqlset/cmd/sqlset-gen --dir=../../testdata/valid_multi --out=queries-gen.go --pkg=main

func main() {
	dir := flag.String("dir", "queries", "directory with .sql files (relative to current working directory)")
	out := flag.String("out", "queries/constants.go", "output file path")
	pkg := flag.String("pkg", "queries", "package name for the generated file")
	flag.Parse()

	fsys := os.DirFS(*dir)

	sqlSet, err := sqlset.New(fsys)
	if err != nil {
		log.Fatalf("failed to load sqlset from %q: %v", *dir, err)
	}

	generated, err := GenerateFileContent(sqlSet, *pkg, strings.Join(os.Args[1:], " "))
	if err != nil {
		log.Fatalf("failed to generate content: %v", err)
	}

	formatted, err := format.Source([]byte(generated))
	if err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile(*out, []byte(formatted), 0644); err != nil {
		log.Fatalf("failed to write output file: %v", err)
	}

	fmt.Printf("Generated: %s (based on %d sets)\n", *out, len(sqlSet.GetSetsMetas()))
}

func GenerateFileContent(sqlSet *sqlset.SQLSet, pkgName, cmd string) (string, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	sb.WriteString("// Code generated by sqlset-gen. DO NOT EDIT.\n")
	sb.WriteString("// Source: github.com/istovpets/sqlset.\n\n")
	sb.WriteString("// Generated by this command:\n")
	sb.WriteString(fmt.Sprintf("// go run github.com/istovpets/sqlset/cmd/sqlset-gen %s\n\n", cmd))

	var setIDs []string
	for _, meta := range sqlSet.GetSetsMetas() {
		if meta.ID != "" {
			setIDs = append(setIDs, meta.ID)
		}
	}
	sort.Strings(setIDs)

	for i, setID := range setIDs {
		if i > 0 {
			sb.WriteString("\n")
		}

		queryIDs, err := sqlSet.GetQueryIDs(setID)
		if err != nil {
			return "", fmt.Errorf("getting queries for %q: %w", setID, err)
		}
		if len(queryIDs) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("// %s.sql\n", setID))
		sb.WriteString(fmt.Sprintf("var %s = struct {\n", toCamel(setID)))

		sort.Strings(queryIDs)

		queryes := make([][2]string, len(queryIDs))
		for i, qID := range queryIDs {
			queryes[i][0] = toCamel(qID)
			queryes[i][1] = setID + "." + qID
		}

		for _, q := range queryes {
			sb.WriteString(fmt.Sprintf("\t%s string\n", q[0]))
		}

		sb.WriteString("}{\n")

		for _, q := range queryes {
			sb.WriteString(fmt.Sprintf("\t%s: %q,\n", q[0], q[1]))
		}

		sb.WriteString("}\n")
	}

	return sb.String(), nil
}

// toCamel converts snake_case or kebab-case to CamelCase
func toCamel(s string) string {
	s = strings.ReplaceAll(s, "-", " ")
	s = strings.ReplaceAll(s, "_", " ")
	parts := strings.Fields(s)

	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}

	return b.String()
}
